[package]
name = "timetable-app"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
uniffi = { version = "0.23.0", features = [ "cli" ] }

[build-dependencies]
uniffi = { version = "0.23.0", features = [ "build" ] }
