[tasks.uniffi]
command = "cargo"
args = [
    "run","--features=uniffi/cli",
    "--bin","uniffi-bindgen",
    "generate","src/timetable.udl",
    "--language","kotlin",
    "--out-dir","../platforms/android/app/src/main/java",
    "--lib-file","target/debug/libtimetable.so"
]
dependencies = ["build"]

[tasks.build]
command = "cargo"
args = ["build"]

[tasks.clean]
cwd = "../platforms/android"
command = "./gradlew"
args = ["clean"]

[tasks.android]
cwd = "../platforms/android"
command = "./gradlew"
args = ["cargoBuild"]
dependencies = ["clean", "uniffi"]
